#include "ChessBoard.hpp"
#include "SamuelEngine.hpp"
#include <cxxtest/TestSuite.h>
#include <iostream>
class TestBoard : public CxxTest::TestSuite {
	public:
		void testChessBoardMemberConstructor() {
			std::vector<std::vector<PiecePtr>> pieces = {};
			bool whiteToMove = true;
			PlayerState whitePlayerState = {true, true};
			PlayerState blackPlayerState = {true, true};
			int halfmove_clock = 0;
			int fullmove_clock = 0;
			Square enPassant_targetSquare = {-1, -1};

			ChessBoard myBoard = ChessBoard(pieces, whiteToMove, whitePlayerState, blackPlayerState, halfmove_clock, fullmove_clock, enPassant_targetSquare);
			(void)myBoard;
		}

		void testChessBoardStreamout() {
			std::vector<std::vector<PiecePtr>> pieces = {};
			bool whiteToMove = true;
			PlayerState whitePlayerState = {true, true};
			PlayerState blackPlayerState = {true, true};
			int halfmove_clock = 0;
			int fullmove_clock = 0;
			Square enPassant_targetSquare = {-1, -1};

			ChessBoard myBoard = ChessBoard(pieces, whiteToMove, whitePlayerState, blackPlayerState, halfmove_clock, fullmove_clock, enPassant_targetSquare);

			std::ostringstream os;
			os << myBoard << std::endl;
		}

		void testChessBoardFenConstructor() {
			// generated by http://bernd.bplaced.net/fengenerator/fengenerator.html; feel free to change this
			std::string myFen = "7B/R1Np1P2/6p1/P3p3/p3P3/K4R1q/1Nk4P/8 w - - 0 1";
			ChessBoard myBoard = ChessBoard(myFen);
			(void)myBoard;
		}
		void testEnPassantWhite() {
			std::string myFen = "rnbqkbnr/1pppp1pp/8/p3Pp2/8/7P/PPPP1PP1/RNBQKBNR w KQkq f6 0 4";
			ChessBoard myBoard = ChessBoard(myFen);
			TS_ASSERT_EQUALS(*myBoard.getEnPassantTargetSquare(), Square("f6"));
			TS_ASSERT_EQUALS(myBoard.getPiece(Square("e5"))->symbol(), 'P');
			TS_ASSERT(myBoard.isMoveLegal(Move(Square("e5"), Square("f6"))))
			myBoard.processMove(Move(Square("e5"), Square("f6")));
			TS_ASSERT(myBoard.getPiece(Square("f6")));
			TS_ASSERT_EQUALS(myBoard.getPiece(Square("f6"))->symbol(), 'P');
			TS_ASSERT(!myBoard.getPiece(Square("f5")));
		}
		void testEnPassantBlack() {
			std::string myFen = "rnbqkbnr/pppp1ppp/8/8/P3pP2/8/1PPPP1PP/RNBQKBNR b KQkq f3 0 4";
			ChessBoard myBoard = ChessBoard(myFen);
			TS_ASSERT_EQUALS(*myBoard.getEnPassantTargetSquare(), Square("f3"));
			TS_ASSERT_EQUALS(myBoard.getPiece(Square("e4"))->symbol(), 'p');
			TS_ASSERT(myBoard.isMoveLegal(Move(Square("e4"), Square("f3"))));
			myBoard.processMove(Move(Square("e4"), Square("f3")));
			TS_ASSERT_EQUALS(myBoard.getPiece(Square("f3"))->symbol(), 'p');
			TS_ASSERT_EQUALS(myBoard.getPiece(Square("f4")), nullptr);
		}
		void testStartingPosNotCheckmate() {
			ChessBoard myBoard = ChessBoard();
			TS_ASSERT(!myBoard.isInCheckmate());
			TS_ASSERT(!isGameOver(myBoard.getStatus()));
			TS_ASSERT_EQUALS(myBoard.perft(1), 20);
			TS_ASSERT_EQUALS(myBoard.perft(2), 400);
			TS_ASSERT_EQUALS(myBoard.perft(3), 8902);
		}
		void testPerfPosition2() {
			// credit to https://chessprogramming.org/Perft_Results for providing the position and correct perft results
			ChessBoard myBoard = ChessBoard("r3k2r/p1ppqpb1/bn2pnp1/3PN3/1p2P3/2N2Q1p/PPPBBPPP/R3K2R w KQkq - 0 1");
			// will only work when castling is implemented
			TS_ASSERT_EQUALS(myBoard.perft(1), 48);
			TS_ASSERT_EQUALS(myBoard.perft(2), 2039);
		}
		void testPerftPositionThree() {
			// also from PerftResults
			ChessBoard myBoard("8/2p5/3p4/KP5r/1R3p1k/8/4P1P1/8 w - - 0 1");
			TS_ASSERT_EQUALS(myBoard.perft(1), 14);
			TS_ASSERT_EQUALS(myBoard.perft(2), 191);
			TS_ASSERT_EQUALS(myBoard.perft(3), 2812);
		}

		void testPerftPositionFour() {
			ChessBoard myBoard("8/P6k/8/8/8/8/8/7K w - - 0 1");
			TS_ASSERT_EQUALS(myBoard.perft(1), 7);
			TS_ASSERT_EQUALS(myBoard.perft(2), 31);
			TS_ASSERT_EQUALS(myBoard.perft(3), 340);
            TS_ASSERT_EQUALS(myBoard.perft(4), 1864);
        }
		void testWhiteKingsideCastling() {
			ChessBoard myBoard("6k1/8/8/8/8/8/8/4K2R w K - 0 1");
			TS_ASSERT(myBoard.getWhitePlayerState().canKingsideCastle);
			TS_ASSERT_EQUALS(myBoard.findKing(true), "e1");
			TS_ASSERT(myBoard.isMoveLegal(Move("e1", "g1")));
			try {
				myBoard.processMove(Move("e1", "g1"));
			} catch (IllegalMoveError &err) {
				TS_FAIL("move from e1 to g1 not legal");
			}
			try {
				TS_ASSERT(myBoard.getAndAssertPiece("g1", 'K'));
			} catch (WrongPieceType &err) {
				TS_FAIL("g1 does not contain king");
			}
			try {
				TS_ASSERT(myBoard.getAndAssertPiece("f1", 'R'));
			} catch (WrongPieceType &err) {
				TS_FAIL("f1 does not contain rook");
			}
			TS_ASSERT(!myBoard.hasPiece("e1"));
			TS_ASSERT(!myBoard.hasPiece("h1"));
		}
		void testWhiteQueensideCastling() {
			ChessBoard myBoard("6k1/8/8/8/8/8/8/R3K3 w Q - 0 1");
			TS_ASSERT(myBoard.getWhitePlayerState().canQueensideCastle);
			TS_ASSERT(myBoard.isMoveLegal(Move("e1", "c1")));
			try {
				myBoard.processMove(Move("e1", "c1"));
			} catch (IllegalMoveError &err) {
				TS_FAIL("move from e1 to c1 not legal");
			}
			try {
				TS_ASSERT(myBoard.getAndAssertPiece("c1", 'K'));
			} catch (WrongPieceType &err) {
				TS_FAIL("c1 does not contain king");
			}
			try {
				TS_ASSERT(myBoard.getAndAssertPiece("d1", 'R'));
			} catch (WrongPieceType &err) {
				TS_FAIL("f1 does not contain rook");
			}
			TS_ASSERT(!myBoard.hasPiece("e1"));
			TS_ASSERT(!myBoard.hasPiece("a1"));
		}
		void testBlackKingsideCastling() {
			ChessBoard myBoard("4k2r/8/8/8/8/8/8/6K1 b k - 0 1");
			TS_ASSERT(myBoard.getBlackPlayerState().canKingsideCastle);
			TS_ASSERT_EQUALS(myBoard.findKing(false), "e8");
			TS_ASSERT(myBoard.isMoveLegal(Move("e8", "g8")));
			try {
				myBoard.processMove(Move("e8", "g8"));
			} catch (IllegalMoveError &err) {
				TS_FAIL("move from e8 to g8 not legal");
			}
			try {
				TS_ASSERT(myBoard.getAndAssertPiece("g8", 'K'));
			} catch (WrongPieceType &err) {
				TS_FAIL("g8 does not contain king");
			}
			try {
				TS_ASSERT(myBoard.getAndAssertPiece("f8", 'R'));
			} catch (WrongPieceType &err) {
				TS_FAIL("f8 does not contain rook");
			}
			TS_ASSERT(!myBoard.hasPiece("e8"));
			TS_ASSERT(!myBoard.hasPiece("h8"));
		}
		void testBlackQueensideCastling() {
			ChessBoard myBoard("r3k3/8/8/8/8/8/8/6K1 b q - 0 1");
			TS_ASSERT(myBoard.getBlackPlayerState().canQueensideCastle);
			TS_ASSERT(myBoard.isMoveLegal(Move("e8", "c8")));
			try {
				myBoard.processMove(Move("e8", "c8"));
			} catch (IllegalMoveError &err) {
				TS_FAIL("move from e8 to c8 not legal");
			}
			try {
				TS_ASSERT(myBoard.getAndAssertPiece("c8", 'K'));
			} catch (WrongPieceType &err) {
				TS_FAIL("c8 does not contain king");
			}
			try {
				TS_ASSERT(myBoard.getAndAssertPiece("d8", 'R'));
			} catch (WrongPieceType &err) {
				TS_FAIL("d8 does not contain rook");
			}
			TS_ASSERT(!myBoard.hasPiece("e8"));
			TS_ASSERT(!myBoard.hasPiece("a8"));
		}
		void testKingDoesNotDisappear() {
			ChessBoard board;
			board.processMove(Move("b1", "c3"));
			board.processMove(Move("d7", "d5"));
			board.processMove(Move("c3", "a4"));
			TS_ASSERT(!board.getEnPassantTargetSquare());
			board.processMove(Move("e8", "d7"));
			board.processMove(Move("a4", "c3"));
			TS_ASSERT(!board.isMoveLegal(Move("e7", "d6")));
			TS_ASSERT_THROWS_ANYTHING(board.processMove(Move("e7", "d6")));
			//std::cout<<board.debug_board()<<std::endl;
			TS_ASSERT_EQUALS(board.findKing(false), Square("d7"));
		}
		void testNoKingFound() {
			ChessBoard myBoard("rnbq1bnr/pp2pppp/3p4/3p4/N7/8/PPPPPPPP/R1BQKBNR b KQ d6 5 4");
			try {
				myBoard.findKing(false);
				TS_FAIL("ERROR: myBoard found a king");
			} catch (std::logic_error &error) {
			}
		}
        void testCastlingPossibleWeirdRegressionTest() {
            ChessBoard board;
            board.processMove({"b1", "c3"});
			board.processMove({"d7", "d6"});
			board.processMove({"g1", "f3"});
			board.processMove({"e8", "d7"});
			board.processMove({"c3", "d5"});
			board.processMove({"a7", "a5"});
			board.processMove({"b2", "b4"});
			board.processMove({"a5", "b4"});
			board.processMove({"f3", "e5"});
			board.processMove({"d6", "e5"});
			board.processMove({"c1", "a3"});
			board.processMove({"a8", "a3"});
			board.processMove({"c2", "c3"});
			board.processMove({"a3", "a2"});
			board.processMove({"a1", "a2"});
			board.processMove({"c7", "c5"});
			board.processMove({"d1", "a4"});
			board.processMove({"d7", "d6"});
			board.processMove({"a4", "b4"});
			board.processMove({"d8", "b6"});
			board.processMove({"b4", "b6"});
			board.processMove({"d6", "d5"});
			board.processMove({"a2", "a1"});
			board.processMove({"b8", "c6"});
			board.processMove({"b6", "b7"});
			board.processMove({"c8", "b7"});
			board.processMove({"e2", "e4"});
			board.processMove({"d5", "e4"});
			board.processMove({"f1", "d3"});
			board.processMove({"e4", "d5"});
			board.processMove({"h2", "h3"});
			board.processMove({"b7", "a8"});
			board.processMove({"h1", "h2"});
			board.processMove({"c6", "a5"});
			board.processMove({"e1", "g1"});
        }
};
