#include "ChessBoard.hpp"
#include "SamuelEngine.hpp"
#include <cxxtest/TestSuite.h>
#include <iostream>
class TestBoard : public CxxTest::TestSuite {
	public:
		void testChessBoardStreamout() {

			ChessBoard myBoard = ChessBoard("8/8/8/8/8/8/8/k6K w KQkq - 0 1");

			std::ostringstream os;
			os << myBoard << std::endl;
		}

		void testChessBoardFenConstructor() {
			// generated by http://bernd.bplaced.net/fengenerator/fengenerator.html; feel free to change this
			std::string myFen = "7B/R1Np1P2/6p1/P3p3/p3P3/K4R1q/1Nk4P/8 w - - 0 1";
			ChessBoard myBoard = ChessBoard(myFen);
			(void)myBoard;
		}
		void testEnPassantWhite() {
			const std::string myFen = "rnbqkbnr/1pppp1pp/8/p3Pp2/8/7P/PPPP1PP1/RNBQKBNR w KQkq f6 0 4";
			ChessBoard myBoard = ChessBoard(myFen);
            TS_ASSERT_EQUALS(myBoard.fen(), myFen);
			TS_ASSERT_EQUALS(*myBoard.getEnPassantTargetSquare(), Square("f6"));
			TS_ASSERT_EQUALS(myBoard.getPiece(Square("e5")).symbol(), 'P');
            TS_ASSERT_EQUALS(myBoard.fen(), myFen);
            try {
                myBoard.verifyZobrist();
            } catch (const std::logic_error& err) {
                TS_FAIL(std::string("error (before checking legality): ") + err.what());
            }
			TS_ASSERT(myBoard.isMoveLegal(
                Move(Square("e5"), Square("f6"), '\0', MoveType::EN_PASSANT)));
            TS_ASSERT_EQUALS(myBoard.fen(), myFen);
            try {
                myBoard.verifyZobrist();
            } catch (const std::logic_error& err) {
                TS_FAIL(std::string("error (after checking legality): ") + err.what());
            }
			myBoard.processMove(Move(Square("e5"), Square("f6"), '\0', MoveType::EN_PASSANT));
            TS_ASSERT(!myBoard.isMoveLegal(Move("e5", "f6")));
			TS_ASSERT(myBoard.getPiece(Square("f6")).isValid());
			TS_ASSERT_EQUALS(myBoard.getPiece(Square("f6")).symbol(), 'P');
			TS_ASSERT(myBoard.getPiece(Square("f5")).isEmpty());
		}
		void testEnPassantBlack() {
			std::string myFen = "rnbqkbnr/pppp1ppp/8/8/P3pP2/8/1PPPP1PP/RNBQKBNR b KQkq f3 0 4";
			ChessBoard myBoard = ChessBoard(myFen);
            TS_ASSERT_EQUALS(myBoard.fen(), myFen);
            try {
                myBoard.verifyZobrist();
            } catch (const std::logic_error& err) {
                TS_FAIL(std::string("error (after making board): ") + err.what());
            }
			TS_ASSERT_EQUALS(*myBoard.getEnPassantTargetSquare(), Square("f3"));
			TS_ASSERT_EQUALS(myBoard.getPiece(Square("e4")).symbol(), 'p');
			TS_ASSERT(myBoard.isMoveLegal(Move(Square("e4"), Square("f3"), '\0', MoveType::EN_PASSANT)));
            try {
                myBoard.verifyZobrist();
            } catch (const std::logic_error& err) {
                TS_FAIL(std::string("error (after checking e4f3EP): ") + err.what());
            }
            TS_ASSERT(!myBoard.isMoveLegal(Move("e4", "f3")));
            TS_ASSERT_EQUALS(myBoard.fen(), myFen);
            try {
                myBoard.verifyZobrist();
            } catch (const std::logic_error& err) {
                TS_FAIL(std::string("error (after checking e4f3, NO EP): ") + err.what());
            }
			myBoard.processMove(Move(Square("e4"), Square("f3"), '\0', MoveType::EN_PASSANT));
            TS_ASSERT_EQUALS(myBoard.fen(), myFen);
            try {
                myBoard.verifyZobrist();
            } catch (const std::logic_error& err) {
                TS_FAIL(std::string("error (after making board): ") + err.what());
            }
			TS_ASSERT_EQUALS(myBoard.getPiece(Square("f3")).symbol(), 'p');
			TS_ASSERT_EQUALS(myBoard.getPiece(Square("f4")), EMPTY_SQUARE);
		}
		void testStartingPosNotCheckmate() {
			ChessBoard myBoard = ChessBoard();
			TS_ASSERT(!myBoard.isInCheckmate());
			TS_ASSERT(!isGameOver(myBoard.getStatus()));
			TS_ASSERT_EQUALS(myBoard.perft(1), 20);
			TS_ASSERT_EQUALS(myBoard.perft(2), 400);
			TS_ASSERT_EQUALS(myBoard.perft(3), 8902);
		}
		void testPerfPosition2() {
			// credit to https://chessprogramming.org/Perft_Results for providing the position and correct perft results
			ChessBoard myBoard = ChessBoard("r3k2r/p1ppqpb1/bn2pnp1/3PN3/1p2P3/2N2Q1p/PPPBBPPP/R3K2R w KQkq - 0 1");
			// will only work when castling is implemented
			TS_ASSERT_EQUALS(myBoard.perft(1), 48);
			TS_ASSERT_EQUALS(myBoard.perft(2), 2039);
		}
		void testKiwinetesA2A4ThenB4A3Legal() {
			ChessBoard myBoard = ChessBoard("r3k2r/p1ppqpb1/bn2pnp1/3PN3/1p2P3/2N2Q1p/PPPBBPPP/R3K2R w KQkq - 0 1");
			myBoard.processMove(Move(Square("a2"), Square("a4")));
			TS_ASSERT_EQUALS(myBoard.fen(), "r3k2r/p1ppqpb1/bn2pnp1/3PN3/Pp2P3/2N2Q1p/1PPBBPPP/R3K2R b KQkq a3 0 1");

			// will only work when castling is implemented
			TS_ASSERT(myBoard.isMoveLegal(Move("b4", "a3")));
			myBoard.processMove(Move("b4", "a3"));
			TS_ASSERT_EQUALS(myBoard.fen(), "r3k2r/p1ppqpb1/bn2pnp1/3PN3/4P3/p1N2Q1p/1PPBBPPP/R3K2R w KQkq - 0 2");
		}
		void testPerftPositionThree() {
			// also from PerftResults
			ChessBoard myBoard("8/2p5/3p4/KP5r/1R3p1k/8/4P1P1/8 w - - 0 1");
			TS_ASSERT_EQUALS(myBoard.perft(1), 14);
			TS_ASSERT_EQUALS(myBoard.perft(2), 191);
			TS_ASSERT_EQUALS(myBoard.perft(3), 2812);
		}

		void testPerftPositionFour() {
			ChessBoard myBoard("8/P6k/8/8/8/8/8/7K w - - 0 1");
			TS_ASSERT_EQUALS(myBoard.perft(1), 7);
			TS_ASSERT_EQUALS(myBoard.perft(2), 31);
			TS_ASSERT_EQUALS(myBoard.perft(3), 340);
			TS_ASSERT_EQUALS(myBoard.perft(4), 1864);
		}
		void testPerftPositionFive() {
			ChessBoard myBoard("r3k2r/Pppp1ppp/1b3nbN/nP6/BBP1P3/q4N2/Pp1P2PP/R2Q1RK1 w kq - 0 1");
			TS_ASSERT_EQUALS(myBoard.perft(1), 6);
			TS_ASSERT_EQUALS(myBoard.perft(2), 264);
			TS_ASSERT_EQUALS(myBoard.perft(3), 9467);
		}
		void testPerftPosFiveAfterB4C5() {
			ChessBoard myBoard("r3k2r/Pppp1ppp/1b3nbN/nP6/BBP1P3/q4N2/Pp1P2PP/R2Q1RK1 w kq - 0 1");
			myBoard.processMove(Move("b4", "c5"));
			TS_ASSERT_EQUALS(myBoard.fen(), "r3k2r/Pppp1ppp/1b3nbN/nPB5/B1P1P3/q4N2/Pp1P2PP/R2Q1RK1 b kq - 1 1");

			TS_ASSERT_EQUALS(myBoard.perft(1), 42);
			TS_ASSERT_EQUALS(myBoard.perft(2), 1352);
			TS_ASSERT(!myBoard.isMoveLegal(Move("b2", "a1", 'B'))); // only promote to black pieces
			TS_ASSERT(myBoard.isMoveLegal(Move("b2", "a1", 'b')));
			myBoard.processMove(Move("b2", "a1", 'b'));

			TS_ASSERT_EQUALS(myBoard.perft(1), 33);
			TS_ASSERT(myBoard.isMoveLegal(Move("d1", "a1")));
		}
		void testPerftPositionSix() {
			ChessBoard myBoard("rnbq1k1r/pp1Pbppp/2p5/8/2B5/8/PPP1NnPP/RNBQK2R w KQ - 1 8");
			TS_ASSERT_EQUALS(myBoard.perft(1), 44);
			TS_ASSERT_EQUALS(myBoard.perft(2), 1486);
		}
		void testPerftPositionSeven() {
			ChessBoard myBoard("r4rk1/1pp1qppp/p1np1n2/2b1p1B1/2B1P1b1/P1NP1N2/1PP1QPPP/R4RK1 w - - 0 10");
			TS_ASSERT_EQUALS(myBoard.get_whiteToMove(), true);
			TS_ASSERT_EQUALS(myBoard.perft(0), 1);
			TS_ASSERT_EQUALS(myBoard.perft(1), 46);
			TS_ASSERT_EQUALS(myBoard.perft(2), 2079);
			TS_ASSERT_EQUALS(myBoard.perft(3), 89890);
		}

        void testUndoPerftStartPos() {
			ChessBoard myBoard = ChessBoard();
			TS_ASSERT_EQUALS(myBoard.perft(1), myBoard.perftCopy(1));
			TS_ASSERT_EQUALS(myBoard.perft(2), myBoard.perftCopy(2));
			TS_ASSERT_EQUALS(myBoard.perft(3), myBoard.perftCopy(3));
		}
		void testUndoPerfPosition2() {
			// credit to https://chessprogramming.org/Perft_Results for providing the position and correct perft results
			ChessBoard myBoard = ChessBoard("r3k2r/p1ppqpb1/bn2pnp1/3PN3/1p2P3/2N2Q1p/PPPBBPPP/R3K2R w KQkq - 0 1");
			// will only work when castling is implemented
			TS_ASSERT_EQUALS(myBoard.perft(1), myBoard.perftCopy(1));
			TS_ASSERT_EQUALS(myBoard.perft(2), myBoard.perftCopy(2));
		}
		void testUndoPerftPositionThree() {
			// also from PerftResults
			ChessBoard myBoard("8/2p5/3p4/KP5r/1R3p1k/8/4P1P1/8 w - - 0 1");
            TS_ASSERT_EQUALS(myBoard.perft(1), myBoard.perftCopy(1));
			TS_ASSERT_EQUALS(myBoard.perft(2), myBoard.perftCopy(2));
			TS_ASSERT_EQUALS(myBoard.perft(3), myBoard.perftCopy(3));
		}

		void testUndoPerftPositionFour() {
			ChessBoard myBoard("8/P6k/8/8/8/8/8/7K w - - 0 1");
			TS_ASSERT_EQUALS(myBoard.perft(1), myBoard.perftCopy(1));
			TS_ASSERT_EQUALS(myBoard.perft(2), myBoard.perftCopy(2));
			TS_ASSERT_EQUALS(myBoard.perft(3), myBoard.perftCopy(3));
            TS_ASSERT_EQUALS(myBoard.perft(4), myBoard.perftCopy(4));
			
		}
		void testUndoPerftPositionFive() {
			ChessBoard myBoard("r3k2r/Pppp1ppp/1b3nbN/nP6/BBP1P3/q4N2/Pp1P2PP/R2Q1RK1 w kq - 0 1");
			TS_ASSERT_EQUALS(myBoard.perft(1), myBoard.perftCopy(1));
			TS_ASSERT_EQUALS(myBoard.perft(2), myBoard.perftCopy(2));
			TS_ASSERT_EQUALS(myBoard.perft(3), myBoard.perftCopy(3));
		}
		
		void testUndoPerftPositionSix() {
			ChessBoard myBoard("rnbq1k1r/pp1Pbppp/2p5/8/2B5/8/PPP1NnPP/RNBQK2R w KQ - 1 8");
			TS_ASSERT_EQUALS(myBoard.perft(1), myBoard.perftCopy(1));
			TS_ASSERT_EQUALS(myBoard.perft(2), myBoard.perftCopy(2));
		}
		void testUndoPerftPositionSeven() {
			ChessBoard myBoard("r4rk1/1pp1qppp/p1np1n2/2b1p1B1/2B1P1b1/P1NP1N2/1PP1QPPP/R4RK1 w - - 0 10");
			TS_ASSERT_EQUALS(myBoard.get_whiteToMove(), true);
			TS_ASSERT_EQUALS(myBoard.perft(0), myBoard.perftCopy(0));
			TS_ASSERT_EQUALS(myBoard.perft(1), myBoard.perftCopy(1));
			TS_ASSERT_EQUALS(myBoard.perft(2), myBoard.perftCopy(2));
			TS_ASSERT_EQUALS(myBoard.perft(3), myBoard.perftCopy(3));
		}
		void testWhiteKingsideCastling() {
			ChessBoard myBoard("6k1/8/8/8/8/8/8/4K2R w K - 0 1");
            ChessBoard oldBoard = myBoard;
			TS_ASSERT(myBoard.getWhitePlayerState().canKingsideCastle);
			TS_ASSERT_EQUALS(myBoard.findKing(Color::WHITE), "e1");
            TS_ASSERT_EQUALS(myBoard.findKing(Color::BLACK), "e8");
			TS_ASSERT(myBoard.isMoveLegal(Move("e1", "g1")));
			try {
				myBoard.processMove(Move("e1", "g1"));
			} catch (IllegalMoveError &err) {
				TS_FAIL("move from e1 to g1 not legal");
			}
			try {
				TS_ASSERT(myBoard.getAndAssertPiece("g1", PieceType::KING).type == PieceType::KING);
			} catch (WrongPieceType &err) {
				TS_FAIL("g1 does not contain king");
			}
			try {
				TS_ASSERT(myBoard.getAndAssertPiece("f1", PieceType::ROOK).type == PieceType::ROOK);
			} catch (WrongPieceType &err) {
				TS_FAIL("f1 does not contain rook");
			}
			TS_ASSERT(!myBoard.hasPiece("e1"));
			TS_ASSERT(!myBoard.hasPiece("h1"));
		}
		void testWhiteQueensideCastling() {
			ChessBoard myBoard("6k1/8/8/8/8/8/8/R3K3 w Q - 0 1");
			TS_ASSERT(myBoard.getWhitePlayerState().canQueensideCastle);
			TS_ASSERT(myBoard.isMoveLegal(Move("e1", "c1")));
			try {
				myBoard.processMove(Move("e1", "c1"));
			} catch (IllegalMoveError &err) {
				TS_FAIL("move from e1 to c1 not legal");
			}
			try {
				TS_ASSERT(myBoard.getAndAssertPiece("c1", PieceType::KING).type == PieceType::KING);
			} catch (WrongPieceType &err) {
				TS_FAIL("c1 does not contain king");
			}
			try {
				TS_ASSERT(myBoard.getAndAssertPiece("d1", PieceType::ROOK).type == PieceType::ROOK);
			} catch (WrongPieceType &err) {
				TS_FAIL("f1 does not contain rook");
			}
			TS_ASSERT(!myBoard.hasPiece("e1"));
			TS_ASSERT(!myBoard.hasPiece("a1"));
		}
		void testBlackKingsideCastling() {
			ChessBoard myBoard("4k2r/8/8/8/8/8/8/6K1 b k - 0 1");
			TS_ASSERT(myBoard.getBlackPlayerState().canKingsideCastle);
			TS_ASSERT_EQUALS(myBoard.findKing(Color::BLACK), "e8");
			TS_ASSERT(myBoard.isMoveLegal(Move("e8", "g8")));
			try {
				myBoard.processMove(Move("e8", "g8"));
			} catch (IllegalMoveError &err) {
				TS_FAIL("move from e8 to g8 not legal");
			}
			try {
				TS_ASSERT(myBoard.getAndAssertPiece("g8", PieceType::KING).type == PieceType::KING);
			} catch (WrongPieceType &err) {
				TS_FAIL("g8 does not contain king");
			}
			try {
				TS_ASSERT(myBoard.getAndAssertPiece("f8", PieceType::ROOK).type == PieceType::ROOK);
			} catch (WrongPieceType &err) {
				TS_FAIL("f8 does not contain rook");
			}
			TS_ASSERT(!myBoard.hasPiece("e8"));
			TS_ASSERT(!myBoard.hasPiece("h8"));
		}
		void testBlackQueensideCastling() {
			ChessBoard myBoard("r3k3/8/8/8/8/8/8/6K1 b q - 0 1");
			TS_ASSERT(myBoard.getBlackPlayerState().canQueensideCastle);
			TS_ASSERT(myBoard.isMoveLegal(Move("e8", "c8")));
			try {
				myBoard.processMove(Move("e8", "c8"));
			} catch (IllegalMoveError &err) {
				TS_FAIL("move from e8 to c8 not legal");
			}
			try {
				TS_ASSERT(myBoard.getAndAssertPiece("c8", PieceType::KING).type == PieceType::KING);
			} catch (WrongPieceType &err) {
				TS_FAIL("c8 does not contain king");
			}
			try {
				TS_ASSERT(myBoard.getAndAssertPiece("d8", PieceType::ROOK).type == PieceType::ROOK);
			} catch (WrongPieceType &err) {
				TS_FAIL("d8 does not contain rook");
			}
			TS_ASSERT(!myBoard.hasPiece("e8"));
			TS_ASSERT(!myBoard.hasPiece("a8"));
		}
		void testKingDoesNotDisappear() {
			ChessBoard board;
			board.processMove(Move("b1", "c3"));
			board.processMove(Move("d7", "d5"));
			board.processMove(Move("c3", "a4"));
			TS_ASSERT(!board.getEnPassantTargetSquare());
			board.processMove(Move("e8", "d7"));
			board.processMove(Move("a4", "c3"));
			TS_ASSERT(!board.isMoveLegal(Move("e7", "d6")));
			TS_ASSERT_THROWS_ANYTHING(board.processMove(Move("e7", "d6")));
			//std::cout<<board.debug_board()<<std::endl;
			TS_ASSERT_EQUALS(board.findKing(Color::BLACK), Square("d7"));
		}
		void testNoKingFound() {
			TS_ASSERT_THROWS_ANYTHING(ChessBoard myBoard("rnbq1bnr/pp2pppp/3p4/3p4/N7/8/PPPPPPPP/R1BQKBNR b KQ d6 5 4"));
		}
        void testFailsWithTwoWhiteKings() {
			TS_ASSERT_THROWS_ANYTHING(ChessBoard myBoard("rnbqkbnr/pp2pppp/3p4/3p4/N7/8/PPPPPPPP/R1BKKBNR b KQ d6 5 4"));
		}
        void testFailsWithTwoBlackKings() {
			TS_ASSERT_THROWS_ANYTHING(ChessBoard myBoard("rnbkkbnr/pp2pppp/3p4/3p4/N7/8/PPPPPPPP/R1BQKBNR b KQ d6 5 4"));
		}
        
		void testCastlingPossibleWeirdRegressionTest() {
			ChessBoard board;
			board.processMove({"b1", "c3"});
			board.processMove({"d7", "d6"});
			board.processMove({"g1", "f3"});
			board.processMove({"e8", "d7"});
			board.processMove({"c3", "d5"});
			board.processMove({"a7", "a5"});
			board.processMove({"b2", "b4"});
			board.processMove({"a5", "b4"});
			board.processMove({"f3", "e5"});
			board.processMove({"d6", "e5"});
			board.processMove({"c1", "a3"});
			board.processMove({"a8", "a3"});
			board.processMove({"c2", "c3"});
			board.processMove({"a3", "a2"});
			board.processMove({"a1", "a2"});
			board.processMove({"c7", "c5"});
			board.processMove({"d1", "a4"});
			board.processMove({"d7", "d6"});
			board.processMove({"a4", "b4"});
			board.processMove({"d8", "b6"});
			board.processMove({"b4", "b6"});
			board.processMove({"d6", "d5"});
			board.processMove({"a2", "a1"});
			board.processMove({"b8", "c6"});
			board.processMove({"b6", "b7"});
			board.processMove({"c8", "b7"});
			board.processMove({"e2", "e4"});
			board.processMove({"d5", "e4"});
			board.processMove({"f1", "d3"});
			board.processMove({"e4", "d5"});
			board.processMove({"h2", "h3"});
			board.processMove({"b7", "a8"});
			board.processMove({"h1", "h2"});
			TS_ASSERT(!board.getWhitePlayerState().canKingsideCastle);
			board.processMove({"c6", "a5"});
			TS_ASSERT_THROWS_ANYTHING(board.processMove({"e1", "g1"}));
		}
		void testDefaultConstructorEverySquare() {
			ChessBoard board;

			// expected[rank][file], rank 0 = white's 1st rank
			const char expected[8][8] = {
				{'R', 'N', 'B', 'Q', 'K', 'B', 'N', 'R'}, // a1-h1
				{'P', 'P', 'P', 'P', 'P', 'P', 'P', 'P'}, // a2-h2
				{0, 0, 0, 0, 0, 0, 0, 0},				  // a3-h3
				{0, 0, 0, 0, 0, 0, 0, 0},				  // a4-h4
				{0, 0, 0, 0, 0, 0, 0, 0},				  // a5-h5
				{0, 0, 0, 0, 0, 0, 0, 0},				  // a6-h6
				{'p', 'p', 'p', 'p', 'p', 'p', 'p', 'p'}, // a7-h7
				{'r', 'n', 'b', 'q', 'k', 'b', 'n', 'r'}, // a8-h8
			};

			for (int rank = 0; rank < 8; ++rank) {
				for (int file = 0; file < 8; ++file) {
					Square sq(file, rank);
					Piece piece = board.getPiece(sq);
					char exp = expected[rank][file];

					if (exp == 0) {
						std::string msg = "expected empty at " + sq.toString();
						TSM_ASSERT(msg.c_str(), piece.isEmpty());
					} else {
						std::string where = sq.toString();
						std::string expStr(1, exp);
						std::string msg1 = "expected " + expStr + " but got empty at " + where;
						TSM_ASSERT(msg1.c_str(), piece.isValid());
						if (piece.isValid()) {
							std::string msg2 = "at " + where;
							TSM_ASSERT_EQUALS(msg2.c_str(), piece.symbol(), exp);
						}
					}
				}
			}

			// your last bug: only 30 pieces instead of 32 (missing h-file)
			int count = 0;
			for (int r = 0; r < 8; ++r)
				for (int f = 0; f < 8; ++f)
					if (board.getPiece(Square(f, r)).isValid())
						count++;
			TS_ASSERT_EQUALS(count, 32);
		}

		void testBlackPawnPromotionColor() {
			// Set up a board where a Black pawn is on rank 1 (index 1) about to promote to rank 0.
			// Replace with your engine's FEN initialization and move generation syntax:
			ChessBoard board("8/8/8/8/8/4k3/4p1K1/8 b - - 0 1");

			TS_ASSERT(!board.isMoveLegal(Move("e2", "e1", '\0')));
			TS_ASSERT(board.isMoveLegal(Move("e2", "e1", 'q')));
			TS_ASSERT(board.isMoveLegal(Move("e2", "e1", 'r')));
			TS_ASSERT(board.isMoveLegal(Move("e2", "e1", 'n')));
			TS_ASSERT(board.isMoveLegal(Move("e2", "e1", 'b')));
			TS_ASSERT(!board.isMoveLegal(Move("e2", "e1", 'Q')));
			TS_ASSERT(!board.isMoveLegal(Move("e2", "e1", 'R')));
			TS_ASSERT(!board.isMoveLegal(Move("e2", "e1", 'N')));
			TS_ASSERT(!board.isMoveLegal(Move("e2", "e1", 'B')));
		}
        void testSixtyQueensCheckmate() {
            ChessBoard board("knQQQQQQ/QnQQQQQQ/QQQQQQQQ/QQQQQQQQ/QQQQQQQQ/QQQQQQQQ/QQQQQQQQ/KQQQQQQQ b - - 0 1");
            TS_ASSERT(board.isInCheck(Color::BLACK));
            TS_ASSERT(board.allLegalMoves().empty());
            TS_ASSERT(board.isInCheckmate());
        }
        void testUndoIsPure() {
            ChessBoard start;
            std::string startFen = start.fen();
        
            auto moves = start.allLegalMoves();
            for (auto &m : moves) {
                ChessBoard b = start; // fresh copy
                b.processMove(m);
                TS_ASSERT_EQUALS(b.getHistory().size(), 1);
                b.undoMove();
                TS_ASSERT_EQUALS(b.fen(), startFen);
                TS_ASSERT_EQUALS(b.getHistory().size(), 0);
                TS_ASSERT_EQUALS(b, start);
            }
        }
        void testThreefoldRepetition() {
            // --- Loop 1 ---
            ChessBoard board;
            uint64_t initial_zobrist = board.getZobrist();
            TS_ASSERT(!board.is_threefold_repetition());
            board.processMove(Move(Square("g1"), Square("f3")));
            board.processMove(Move(Square("b8"), Square("c6")));
            board.processMove(Move(Square("f3"), Square("g1")));
            board.processMove(Move(Square("c6"), Square("b8")));
            TS_ASSERT_EQUALS(board.getZobrist(), initial_zobrist);
            
            // We are back at the starting position (Occurrence #2)
            TS_ASSERT(!board.is_threefold_repetition()); // Only 2 occurrences total (Start + Loop 1)

            // --- Loop 2 ---
            board.processMove(Move(Square("g1"), Square("f3")));
            board.processMove(Move(Square("b8"), Square("c6")));
            board.processMove(Move(Square("f3"), Square("g1")));
            board.processMove(Move(Square("c6"), Square("b8")));
            TS_ASSERT_EQUALS(board.getZobrist(), initial_zobrist);
            TSM_ASSERT("threefold repetition failed", board.is_threefold_repetition()); // Caught it!
            TS_ASSERT(board.getStatus() == GameStatus::DRAW);
            TS_ASSERT(isGameOver(board.getStatus()));
            board.processMove(Move(Square("g1"), Square("f3")));
            board.processMove(Move(Square("b8"), Square("c6")));
            board.processMove(Move(Square("f3"), Square("g1")));
            board.processMove(Move(Square("c6"), Square("b8")));
            TSM_ASSERT_EQUALS("fourfold repetition failed", board.getZobrist(), initial_zobrist);
            TS_ASSERT(board.is_threefold_repetition()); // Caught it!
            TS_ASSERT(board.getStatus() == GameStatus::DRAW);
            TS_ASSERT(isGameOver(board.getStatus()));
        }
};


