#include <cxxtest/TestSuite.h>
#include "ChessBoard.hpp"

class TestBoard: public CxxTest::TestSuite
{
	public:
		void testChessBoardMemberConstructor(){
			std::vector<std::vector<std::shared_ptr<Piece>>> pieces = {};
			bool whiteToMove = true;
			PlayerState whitePlayerState = {true, true};
			PlayerState blackPlayerState = {true, true};
			int halfmove_clock = 0;
			int fullmove_clock = 0;
			Square enPassant_targetSquare = { -1, -1 };

			ChessBoard myBoard = ChessBoard(
				pieces,
				whiteToMove,
				whitePlayerState,
				blackPlayerState,
				halfmove_clock,
				fullmove_clock,
				enPassant_targetSquare
			);
			(void)myBoard;
		}

		void testChessBoardStreamout(){
                        std::vector<std::vector<std::shared_ptr<Piece>>> pieces = {};
                        bool whiteToMove = true;
                        PlayerState whitePlayerState = {true, true};
                        PlayerState blackPlayerState = {true, true};
                        int halfmove_clock = 0;
                        int fullmove_clock = 0;
                        Square enPassant_targetSquare = { -1, -1 };

                        ChessBoard myBoard = ChessBoard(
                                pieces,
                                whiteToMove,
                                whitePlayerState,
                                blackPlayerState,
                                halfmove_clock,
                                fullmove_clock,
                                enPassant_targetSquare
                        );

			std::ostringstream os;
			os << myBoard << std::endl;
                }

		// TODO: fix failing fen constructor
		/*
		void commentedTestChessBoardFenConstructor(){
			// generated by http://bernd.bplaced.net/fengenerator/fengenerator.html; feel free to change this
			std::string myFen = "7B/R1Np1P2/6p1/P3p3/p3P3/K4R1q/1Nk4P/8 w - - 0 1";
			ChessBoard myBoard = ChessBoard(myFen);
			(void)myBoard;
		}
		*/
};
